engines:
  eslint:
    enabled: true
    channel: "eslint-6"
    config:
      config: ".eslintrc.yaml"

ratings:
   paths:
   - "**.js"

checks:
  method-lines:
    config:
      threshold: 50
  method-complexity:
    config:
      threshold: 10
